CREATE TABLE config_meta (singleton SMALLINT PRIMARY KEY CHECK (singleton = 1), revision BIGINT NOT NULL CHECK (revision >= 0));
INSERT INTO config_meta VALUES (1, 0);
CREATE TABLE clients (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revision BIGINT NOT NULL DEFAULT 1 CHECK (revision >= 1),
 name TEXT NOT NULL UNIQUE, enabled BOOLEAN NOT NULL, priority_class TEXT NOT NULL CHECK (priority_class IN ('critical','high','normal','background')),
 vllm_priority INTEGER NOT NULL, max_concurrency INTEGER NOT NULL CHECK (max_concurrency BETWEEN 0 AND 10000),
 requests_per_minute BIGINT NOT NULL DEFAULT 0 CHECK (requests_per_minute BETWEEN 0 AND 10000000),
 tokens_per_minute BIGINT NOT NULL DEFAULT 0 CHECK (tokens_per_minute BETWEEN 0 AND 10000000000000),
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE api_keys (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id BIGINT NOT NULL REFERENCES clients(id), prefix TEXT NOT NULL,
 secret_hash BYTEA NOT NULL CHECK (octet_length(secret_hash)=32), created_at TIMESTAMPTZ NOT NULL,
 expires_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, last_used_at TIMESTAMPTZ);
CREATE INDEX api_keys_prefix_idx ON api_keys(prefix); CREATE INDEX api_keys_client_idx ON api_keys(client_id);
CREATE TABLE model_pools (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revision BIGINT NOT NULL DEFAULT 1 CHECK (revision >= 1),
 public_model_name TEXT NOT NULL UNIQUE, upstream_model_name TEXT NOT NULL, enabled BOOLEAN NOT NULL,
 max_gateway_inflight INTEGER NOT NULL DEFAULT 0 CHECK (max_gateway_inflight BETWEEN 0 AND 100000),
 max_waiting INTEGER NOT NULL DEFAULT 0 CHECK (max_waiting >= 0), created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE client_model_access (client_id BIGINT NOT NULL REFERENCES clients(id), model_pool_id BIGINT NOT NULL REFERENCES model_pools(id), enabled BOOLEAN NOT NULL, PRIMARY KEY(client_id,model_pool_id));
CREATE TABLE backends (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revision BIGINT NOT NULL DEFAULT 1 CHECK (revision >= 1),
 model_pool_id BIGINT NOT NULL REFERENCES model_pools(id), name TEXT NOT NULL UNIQUE, base_url TEXT NOT NULL,
 enabled BOOLEAN NOT NULL, draining BOOLEAN NOT NULL, capacity_hint DOUBLE PRECISION NOT NULL CHECK(capacity_hint>0),
 running_soft_limit DOUBLE PRECISION NOT NULL CHECK(running_soft_limit>0), upstream_api_key_env TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX backends_pool_idx ON backends(model_pool_id);
