CREATE TABLE usage_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at TIMESTAMPTZ NOT NULL, request_id TEXT NOT NULL UNIQUE,
 parent_request_id TEXT NOT NULL DEFAULT '', client_id BIGINT NOT NULL, client_name TEXT NOT NULL, model_pool_id BIGINT NOT NULL,
 model_name TEXT NOT NULL, backend_name TEXT NOT NULL, http_status INTEGER NOT NULL, duration_ms BIGINT NOT NULL,
 ttft_ms BIGINT, retry_count INTEGER NOT NULL, disconnected BOOLEAN NOT NULL, usage_available BOOLEAN NOT NULL,
 input_tokens BIGINT, output_tokens BIGINT, cache_read_tokens BIGINT,
 CHECK ((usage_available AND input_tokens IS NOT NULL AND output_tokens IS NOT NULL) OR (NOT usage_available AND input_tokens IS NULL AND output_tokens IS NULL AND cache_read_tokens IS NULL)));
CREATE INDEX usage_requests_time_idx ON usage_requests(occurred_at DESC,id DESC);
CREATE INDEX usage_requests_client_time_idx ON usage_requests(client_id,occurred_at DESC);
CREATE INDEX usage_requests_model_time_idx ON usage_requests(model_pool_id,occurred_at DESC);
