apiVersion: 1

datasources:
  - name: LLM Gateway Prometheus
    type: prometheus
    uid: llmgw-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 1s
